### ISSUE TITLE
Missing output file(s) `unifire/predictions_arba.out` expected by process `EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE`

### ISSUE THREAD

**Issue by Andrewab9** [EBI-Metagenomics/mettannotator#40]
### Description of the bug

Hello! 

I'm trying to use the pipeline but i got the error in the title.

Hope you can help me!

### Command used and terminal output

```console
This is the command i used:
NXF_VER=23.10.0 nextflow run ebi-metagenomics/mettannotator -r bugfix/38-unifire-mount-docker -profile docker --input assemblies_sheet.csv --outdir output/ --dbs /mnt/hdd2/database/




Here's the terminal output:
ERROR ~ Error executing process > 'EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE (SA2095)'

Caused by:
  Missing output file(s) `unifire/predictions_arba.out` expected by process `EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE (SA2095)`

Command executed:

  echo "Pre-processed UniFIRE input file"
  prepare_unifire_input.py -i unifire/SA2095.faa -t 1280 -o unifire

  # This is the provided docker running script
  /opt/scripts/bin/unifire-workflow.sh

  make_combined_unifire_output.py -i unifire -o unifire/SA2095.combined_predictions.out

  cat <<-END_VERSIONS > versions.yml
  "EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE":
      UniFIRE: 2023.4
  END_VERSIONS

Command exit status:
  0

Command output:
  ebi-meat org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2-1.4.199.jar:1.4.199]
  RN: Kiat org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.199.jar:1.4.199]
        at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.199.jar:1.4.199]
        at org.h2.message.DbException.get(DbException.java:170) ~[h2-1.4.199.jar:1.4.199]
        at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571) ~[h2-1.4.199.jar:1.4.199]
        at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557) ~[h2-1.4.199.jar:1.4.199]
        at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:539) ~[h2-1.4.199.jar:1.4.199]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:385) ~[spring-jdbc-5.2.24.RELEASE.jar:5.2.24.RELEASE]
        at com.sun.proxy.$Proxy30.commit(Unknown Source) ~[?:?]
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:81) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:272) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534) ~[spring-orm-5.2.24.RELEASE.jar:5.2.24.RELEASE]
        ... 10 more
  09:15:49.274 ERROR o.p.p.PIRSRApp - Wrong argument for option -i. No such file or directory: /volume/proteins_lineage-ipr.xml
  java.lang.IllegalArgumentException: Wrong argument for option -i. No such file or directory: /volume/proteins_lineage-ipr.xml
        at org.proteininformationresource.pirsr.PIRSRApp.parseOption(PIRSRApp.java:130)
        at org.proteininformationresource.pirsr.PIRSRApp.main(PIRSRApp.java:87)
  Caused by: java.lang.IllegalArgumentException: No such file or directory: /volume/proteins_lineage-ipr.xml
        at org.proteininformationresource.pirsr.PIRSRApp$FileCreatorChecker.createAndCheck(PIRSRApp.java:145)
        at org.proteininformationresource.pirsr.PIRSRApp.parseOption(PIRSRApp.java:128)
        ... 1 common frames omitted
  09:15:49.753 ERROR u.a.e.u.u.UniFireApp - Wrong argument for option -i. No such file: /volume/proteins_lineage-ipr.xml
  java.lang.IllegalArgumentException: Wrong argument for option -i. No such file: /volume/proteins_lineage-ipr.xml
        at uk.ac.ebi.uniprot.unifire.UniFireApp.parseOption(UniFireApp.java:138)
        at uk.ac.ebi.uniprot.unifire.UniFireApp.main(UniFireApp.java:89)
  Caused by: java.lang.IllegalArgumentException: No such file: /volume/proteins_lineage-ipr.xml
        at uk.ac.ebi.uniprot.unifire.UniFireApp$FileCreatorChecker.createAndCheck(UniFireApp.java:154)
        at uk.ac.ebi.uniprot.unifire.UniFireApp.parseOption(UniFireApp.java:136)
        ... 1 common frames omitted
  09:15:50.174 ERROR u.a.e.u.u.UniFireApp - Wrong argument for option -i. No such file: /volume/proteins_lineage-ipr.xml
  java.lang.IllegalArgumentException: Wrong argument for option -i. No such file: /volume/proteins_lineage-ipr.xml
        at uk.ac.ebi.uniprot.unifire.UniFireApp.parseOption(UniFireApp.java:138)
        at uk.ac.ebi.uniprot.unifire.UniFireApp.main(UniFireApp.java:89)
  Caused by: java.lang.IllegalArgumentException: No such file: /volume/proteins_lineage-ipr.xml
        at uk.ac.ebi.uniprot.unifire.UniFireApp$FileCreatorChecker.createAndCheck(UniFireApp.java:154)
        at uk.ac.ebi.uniprot.unifire.UniFireApp.parseOption(UniFireApp.java:136)
        ... 1 common frames omitted
  09:15:50.641 ERROR u.a.e.u.u.UniFireApp - Wrong argument for option -i. No such file: /volume/proteins_lineage-ipr-urml.xml
  java.lang.IllegalArgumentException: Wrong argument for option -i. No such file: /volume/proteins_lineage-ipr-urml.xml
        at uk.ac.ebi.uniprot.unifire.UniFireApp.parseOption(UniFireApp.java:138)
        at uk.ac.ebi.uniprot.unifire.UniFireApp.main(UniFireApp.java:89)
  Caused by: java.lang.IllegalArgumentException: No such file: /volume/proteins_lineage-ipr-urml.xml
        at uk.ac.ebi.uniprot.unifire.UniFireApp$FileCreatorChecker.createAndCheck(UniFireApp.java:154)
        at uk.ac.ebi.uniprot.unifire.UniFireApp.parseOption(UniFireApp.java:136)
        ... 1 common frames omitted

Command error:
      for seq_record in SeqIO.parse(open(file_in, mode='r'), "fasta"):
  FileNotFoundError: [Errno 2] No such file or directory: '/volume/proteins.fasta'
  org.springframework.orm.jpa.JpaSystemException: org.hibernate.TransactionException: Unable to commit against JDBC Connection; nested exception is javax.persistence.PersistenceException: org.hibernate.TransactionException: Unable to commit against JDBC Connection
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:408)
        at org.springframework.orm.jpa.DefaultJpaDialect.translateExceptionIfPossible(DefaultJpaDialect.java:128)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:538)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:633)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy83.retrieveUnfinishedStepInstances(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:262)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:413)
  Caused by: javax.persistence.PersistenceException: org.hibernate.TransactionException: Unable to commit against JDBC Connection
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:60)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:107)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534)
        ... 10 more
  Caused by: org.hibernate.TransactionException: Unable to commit against JDBC Connection
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:87)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:272)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
        ... 11 more
  Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.message.DbException.get(DbException.java:170)
        at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
        at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
        at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:539)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:385)
        at com.sun.proxy.$Proxy30.commit(Unknown Source)
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:81)
        ... 13 more
  InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
  stat: cannot stat '/volume/proteins.fasta': No such file or directory
  chown: missing operand after '/volume/proteins_lineage.fasta'
  Try 'chown --help' for more information.
  ERROR:root:File predictions_arba.out does not exist in folder unifire. Aborting.

Work dir:
  /mnt/hdd3/andre/s_aureus/fasta_pilon_2_run/metannotator/work/55/b179801e65c17870f9013390e4d984

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

### Relevant files

[.nextflow.log](https://github.com/user-attachments/files/16246590/default.nextflow.log)

**Comment by mberacochea** [comment]
Hi @Andrewab9,

Thank you for reporting this problem, from the log file it seems that docker + Unifire are not playing along nicely:
```
  InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details
  stat: cannot stat '/volume/proteins.fasta': No such file or directory
  chown: missing operand after '/volume/proteins_lineage.fasta'
  Try 'chown --help' for more information.
  ERROR:root:File predictions_arba.out does not exist in folder unifire. Aborting.
```
I'm trying to reproduce and fix this one, I'll keep you posted. This is related to #38

Cheers

**Comment by mberacochea** [comment]
Hi @Andrewab9 

I was able to reproduce this issue and managed to fix it (at least on my environment), the problem was that both unifire and interpro mounted volumes were using a relative paths which docker doesn't like. I've changed that, and also added a fix emapper (https://github.com/EBI-Metagenomics/mettannotator/pull/42/files#diff-3d84166c14279a1e83f4344e03add770c5dde9239645b80b9a3ceac5ca8a983fR22).

Can you please from the following branch "[bugfix/ips-unipro-docker-mounts-fix](https://github.com/EBI-Metagenomics/mettannotator/tree/bugfix/ips-unipro-docker-mounts-fix)"?

```
$ nextflow run ebi-metagenomics/mettannotator -r  bugfix/ips-unipro-docker-mounts-fix ...
```

**Comment by Andrewab9** [comment]
Hi @mberacochea,
It ran without problems. Thank you so much!

**Comment by mberacochea** [comment]
> Hi @mberacochea, It ran without problems. Thank you so much! Just one thing: I've tried to use the latest version of Interproscan, but it uses the default version anyway,
> 
> `NXF_VER=23.04.3 nextflow run ebi-metagenomics/mettannotator/main.nf -r bugfix/ips-unipro-docker-mounts-fix --input $(pwd)/assemblies_sheet.csv -profile docker --outdir $(pwd)/metannotator_results --multiqc_title SA --dbs /mnt/hdd2/database/ --interproscan_db /mnt/hdd2/database/interproscan-5.68-100.0/ --interproscan_db_version 5.68-100.0 `

That is great news, thanks for testing that.

Regarding the version of InterProScan, the pipeline doesn't support overriding individual databases in that manner. If you specify the --dbs parameter, the pipeline will source all databases from that folder. I understand this can be confusing, as individual database flags should ideally override the default ones. However, I don't have the capacity to adjust this at the moment. My suggestion is to copy the IPS database version into the --dbs folder, create a VERSION.txt file in the directory, and add the version '5.68-100.0' to it.

I'm closing this ticket as the bug has been fixed. I'll adjust the documentation to highlight the caveat regarding the --dbs parameter.
